// Mock catalogue for the Арома Ателье guest kit — real mixes from docs/data/top-20-mixes.md.
window.AROMA_MOCK = {
  profileLabels: {
    sweet: 'Сладкий', sour: 'Кислый', spicy: 'Пряный', fresh: 'Свежий', dessert: 'Десертный',
    tobacco: 'Табачный', minty: 'Мятный', fruity: 'Фруктовый', floral_herbal: 'Цветочно-травяной',
    citrus: 'Цитрусовый', berry: 'Ягодный', perfume: 'Парфюмный',
  },
  flavors: ['земляника', 'лесные ягоды', 'чёрный чай', 'кола', 'банан', 'манго', 'мороженое', 'клубника', 'лимон', 'ананас', 'апельсин', 'корица', 'дыня', 'мята', 'мандарин', 'молоко', 'черника', 'печенье', 'чизкейк', 'виноград'],
  introCards: [
    { id: 'i1', title: 'Мы подберём микс под ваше настроение', description: 'Пара вопросов о вкусах — и подбор соберётся из того, что реально есть на кухне сегодня.' },
    { id: 'i2', title: 'Витрина — если хочется выбрать глазами', description: 'Подборки редакции, миксы мастеров зала и то, что чаще всего выбирают гости.' },
    { id: 'i3', title: 'Каталог — если точно знаете, что ищете', description: 'Поиск и фильтры по категориям и вкусам. Недоступные позиции не показываем.' },
    { id: 'i4', title: 'Готово — покажите карточку мастеру', description: 'Нажмите «Покурить», и на экране останется чистая карточка с составом.' },
  ],
  mixes: [
    { id: 'm1', name: 'Морозная ягода', description: 'Земляника и лесные ягоды на чёрном чае, с холодком.', flavorProfiles: ['berry', 'fresh'], flavors: ['земляника', 'лесные ягоды', 'чёрный чай'], avgRating: 4.7, popularity: 214,
      components: [{ id: 'c1', name: 'Red Tea', manufacturer: 'Darkside', proportion: 50 }, { id: 'c2', name: 'Wildberry', manufacturer: 'Darkside', proportion: 40 }, { id: 'c3', name: 'Supernova', manufacturer: 'Darkside', proportion: 10 }] },
    { id: 'm2', name: 'Космокола', description: 'Газировка с цветочной нотой и ледяным финалом.', flavorProfiles: ['sweet', 'floral_herbal'], flavors: ['кола', 'цветочный'], avgRating: 4.4, popularity: 168,
      components: [{ id: 'c4', name: 'Cosmo Flower', manufacturer: 'Darkside', proportion: 45 }, { id: 'c5', name: 'Cola', manufacturer: 'Darkside', proportion: 30 }, { id: 'c6', name: 'Supernova', manufacturer: 'Darkside', proportion: 25 }] },
    { id: 'm3', name: 'Тропики', description: 'Банан и манго-ласси — плотно и сладко, без холодка.', flavorProfiles: ['fruity', 'dessert'], flavors: ['банан', 'манго', 'йогурт'], avgRating: 4.5, popularity: 151,
      components: [{ id: 'c7', name: 'Bananapapa', manufacturer: 'Darkside', proportion: 60 }, { id: 'c8', name: 'Mango Lassi', manufacturer: 'Darkside', proportion: 40 }] },
    { id: 'm4', name: 'Клубничный лёд', description: 'Клубника с мороженым — самый спокойный вход для новичка.', flavorProfiles: ['berry', 'dessert'], flavors: ['клубника', 'мороженое'], avgRating: 4.3, popularity: 139,
      components: [{ id: 'c9', name: 'Strawberry Light', manufacturer: 'Darkside', proportion: 70 }, { id: 'c10', name: 'Dark Icecream', manufacturer: 'Darkside', proportion: 30 }] },
    { id: 'm5', name: 'Lemon Pineapple', description: 'Кислинка лимона на ананасовой базе.', flavorProfiles: ['citrus', 'fruity'], flavors: ['лимон', 'ананас'], avgRating: 4.2, popularity: 121,
      components: [{ id: 'c11', name: 'Lemonblast', manufacturer: 'Darkside', proportion: 65 }, { id: 'c12', name: 'Pineapple', manufacturer: 'Serbetli', proportion: 35 }] },
    { id: 'm6', name: 'Pirate Citrus', description: 'Апельсин и мандарин с ром-пуншем, лёгкий холодок.', flavorProfiles: ['citrus', 'sweet'], flavors: ['апельсин', 'мандарин', 'ром-пунш'], avgRating: 4.6, popularity: 118,
      components: [{ id: 'c13', name: 'Orange Team', manufacturer: 'MustHave', proportion: 50 }, { id: 'c14', name: 'Pirates Cave', manufacturer: 'Starbuzz', proportion: 40 }, { id: 'c15', name: 'Ice Mint', manufacturer: 'MustHave', proportion: 10 }] },
    { id: 'm7', name: 'Cinnamon Red Tea', description: 'Корица и чёрный чай — согревающий осенний микс.', flavorProfiles: ['spicy', 'tobacco'], flavors: ['корица', 'чёрный чай'], avgRating: 4.1, popularity: 96,
      components: [{ id: 'c16', name: 'Cinnamon Roll', manufacturer: 'MustHave', proportion: 50 }, { id: 'c17', name: 'Red Tea', manufacturer: 'Darkside', proportion: 50 }] },
    { id: 'm8', name: 'Pineapple Mint', description: 'Ананас с мятой — свежо и легко.', flavorProfiles: ['fruity', 'minty'], flavors: ['ананас', 'мята'], avgRating: 4.4, popularity: 108,
      components: [{ id: 'c18', name: 'Pineapple Rings', manufacturer: 'MustHave', proportion: 70 }, { id: 'c19', name: 'Мята', manufacturer: 'BlackBurn', proportion: 30 }] },
    { id: 'm9', name: 'Лимонный пирог', description: 'Гастро-десертка: лимонный пирог на молоке.', flavorProfiles: ['dessert', 'citrus'], flavors: ['лимонный пирог', 'молоко'], avgRating: 4.5, popularity: 87,
      components: [{ id: 'c20', name: 'Lemon Pie', manufacturer: 'Adalya', proportion: 70 }, { id: 'c21', name: 'Молоко', manufacturer: 'Adalya', proportion: 30 }] },
    { id: 'm10', name: 'Cheesecake Wild Forest', description: 'Чизкейк, лесные ягоды и виноградный холодок.', flavorProfiles: ['dessert', 'berry'], flavors: ['чизкейк', 'лесные ягоды', 'виноград'], avgRating: 4.8, popularity: 176,
      components: [{ id: 'c22', name: 'Cheesecake', manufacturer: 'Spectrum', proportion: 40 }, { id: 'c23', name: 'Wild Forest', manufacturer: 'Spectrum', proportion: 30 }, { id: 'c24', name: 'Ice Granny', manufacturer: 'BlackBurn', proportion: 30 }] },
    { id: 'm11', name: 'Молоко-Черника', description: 'Черника с молоком — сладко и просто.', flavorProfiles: ['berry', 'dessert'], flavors: ['молоко', 'черника'], avgRating: 4.0, popularity: 74,
      components: [{ id: 'c25', name: 'Черника', manufacturer: 'Adalya', proportion: 70 }, { id: 'c26', name: 'Молоко', manufacturer: 'Adalya', proportion: 30 }] },
    { id: 'm12', name: 'Bodrum Tangerine', description: 'Мандарин, мята и жвачка — освежающая классика.', flavorProfiles: ['citrus', 'minty'], flavors: ['мандарин', 'мята', 'жвачка'], avgRating: 4.2, popularity: 92,
      components: [{ id: 'c27', name: 'Bodrum Tangerine', manufacturer: 'Serbetli', proportion: 50 }, { id: 'c28', name: 'Fresh Mist', manufacturer: 'AlFakher', proportion: 30 }, { id: 'c29', name: 'Жвачка', manufacturer: 'AlFakher', proportion: 20 }] },
  ],
  rails: [
    { id: 'r1', name: 'Больше всего выбирают', type: 'statistical', description: 'Миксы, к которым гости возвращаются чаще всего.', mixIds: ['m1', 'm10', 'm2', 'm3', 'm4'] },
    { id: 'r2', name: 'Вечер в ателье', type: 'prepared', description: 'Подборка для быстрого старта в фирменной стилистике ателье.', mixIds: ['m9', 'm7', 'm10', 'm11'] },
    { id: 'r3', name: 'Советуют мастера', type: 'curated', description: 'Выразительные сочетания, которые чаще советуют мастера зала.', mixIds: ['m6', 'm5', 'm8', 'm12'] },
  ],
};
