ALTER TYPE "FlavorProfile" ADD VALUE IF NOT EXISTS 'minty';
ALTER TYPE "FlavorProfile" ADD VALUE IF NOT EXISTS 'fruity';
ALTER TYPE "FlavorProfile" ADD VALUE IF NOT EXISTS 'floral_herbal';
ALTER TYPE "FlavorProfile" ADD VALUE IF NOT EXISTS 'citrus';
ALTER TYPE "FlavorProfile" ADD VALUE IF NOT EXISTS 'berry';

ALTER TABLE "Tobacco"
ADD COLUMN "flavors" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Tobacco"
ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Mix"
ADD COLUMN "flavors" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
